<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
		<AssemblyName>SuperNewRoles</AssemblyName>
        <Description>SuperNewRoles</Description>
        <Authors>ykundesu</Authors>
        <Version>2.2.3.1</Version>
        <langVersion>preview</langVersion>
		<DebugType>embedded</DebugType>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<Configurations>Debug;Release;</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<AmongUs>F:\AmongUs\v2024.3.5-SNR</AmongUs>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AmongUs.GameLibs.Steam" Version="2024.6.4" />
		<PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.669" />
		<Reference Include="..\.lib\Agartha.dll" />
		<PackageReference Include="BepInEx.AutoPlugin" Version="1.0.1" PrivateAssets="all" />
	</ItemGroup>

	<Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="Exists('$(AmongUs)/BepInEx/plugins/')">
		<Message Text="Second occurrence" />
		<Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\net6.0\$(AssemblyName).dll" DestinationFolder="$(AmongUs)/BepInEx/plugins/" />
	</Target>
</Project>
